name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest]
        dotnet-version: ['8.0.x']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    
    - name: Restore dependencies
      run: dotnet restore BestPracticesMCP.sln
    
    - name: Build
      run: dotnet build BestPracticesMCP.sln --no-restore --configuration Release
    
    - name: Test
      run: dotnet test BestPracticesMCP.sln --no-build --configuration Release --verbosity normal

  docker-build:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image - HTTP
      run: |
        docker build -f BestPracticesMCP-HTTP/Dockerfile -t bestpracticesmcp-http:latest .
    
    - name: Build Docker image - HTTP Auth
      run: |
        docker build -f BestPracticesMCP-HTTP-Auth/Dockerfile -t bestpracticesmcp-http-auth:latest .
    
    - name: Test Docker images
      run: |
        docker images | grep bestpracticesmcp
